version: '3.3'
volumes:
  capsule-data:

services:
  capsule:
    image: ghcr.io/timecapsulellc/capsule
    command: --listen 0.0.0.0 --port 7865
    ports:
      - 7865:7865
    volumes:
      - capsule-data:/content/data
      - ./:/app/Capsule
    environment:
      - path_checkpoints=/content/data/models/checkpoints/
      - path_loras=/content/data/models/loras/
      - path_embeddings=/content/data/models/embeddings/
      - path_vae_approx=/content/data/models/vae_approx/
      - path_vae=/content/data/models/vae/
      - path_upscale_models=/content/data/models/upscale_models/
      - path_inpaint=/content/data/models/inpaint/
      - path_controlnet=/content/data/models/controlnet/
      - path_clip_vision=/content/data/models/clip_vision/
      - path_capsule_expansion=/content/data/models/prompt_expansion/capsule_expansion/
      - path_wildcards=/content/data/wildcards/
      - path_outputs=/content/data/outputs/
